language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:

script:
    - vendor/bin/tester -w tests/reCAPTCHA -p php -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

before_script:
    # Update Composer
    - composer self-update

    # Install Nette Tester
    - composer install --no-interaction --prefer-source
